### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by zxclinwy** [VladislavAlpatov/kittenhook#1]
I found this cheat on Apex but I don’t know what to do with it, because I actually wanted to just download it from release, but then it turned out that it wasn’t there.

**Comment by VladislavAlpatov** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./cmake-build-release
cmake --build ./cmake-build-release --target kittenhook -- -j 6

**Comment by zxclinwy** [comment]
Where should I write this?

**Comment by VladislavAlpatov** [comment]
> Where should I write this?

in root of project

**Comment by zxclinwy** [comment]
I'm sorry but what is root, is it the command line for developers in vs 2022? or whatever it is.

**Comment by zxclinwy** [comment]
You can write a tutorial on how to build this project using cmake, I just have errors and that’s all.

**Comment by zxclinwy** [comment]
please

**Comment by VladislavAlpatov** [comment]
> please

its a linux cheat...
